name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    branches:
       - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Replace with the desired Python version

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Build Project Artifacts
        run: | 
          mkdir vercel
          cp -r dashapp vercel/
          cp -r database vercel/
          cp requirements.txt vercel/
          cp vercel.json vercel/
          cd vercel
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          cd vercel
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz --prod
