name: Scrape Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

env:
  LANG: "es_ES.UTF-8"
  LANGUAGE: "es_ES:es"
  LC_ALL: "es_ES.UTF-8"

jobs:
  scrape_abc:
    runs-on: ubuntu-latest
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: compute-cache-key
        run: echo "CACHE_KEY=${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}" >> $GITHUB_ENV

      - name: Restore Python packages from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}

      - name: Scrape ABC
        run: |
          echo "XATA_API_KEY=${{ secrets.XATA_API_KEY }}" >> .env
          echo "XATA_DB_URL=${{ secrets.XATA_DB_URL }}" >> .env
          make scrape LIMIT=50 BRANCH=main SITES=abc

  scrape_ultimahora:
    runs-on: ubuntu-latest
    needs: scrape_abc
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v4

      - name: Restore Python packages from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}

      - name: Scrape UltimaHora
        run: |
          echo "XATA_API_KEY=${{ secrets.XATA_API_KEY }}" >> .env
          echo "XATA_DB_URL=${{ secrets.XATA_DB_URL }}" >> .env
          make scrape LIMIT=50 BRANCH=main SITES=ultimahora

  scrape_lanacion:
    runs-on: ubuntu-latest
    needs: scrape_ultimahora
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v4

      - name: Restore Python packages from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}

      - name: Scrape LaNacion
        run: |
          echo "XATA_API_KEY=${{ secrets.XATA_API_KEY }}" >> .env
          echo "XATA_DB_URL=${{ secrets.XATA_DB_URL }}" >> .env
          make scrape LIMIT=50 BRANCH=main SITES=lanacion