name: Scrape Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
  workflow_run:
    workflows: ["Setup Environment"]
    types:
      - completed

env:
  LANG: "es_ES.UTF-8"
  LANGUAGE: "es_ES:es"
  LC_ALL: "es_ES.UTF-8"

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: ["abc", "ultimahora", "lanacion", "cincodias"]
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: compute-cache-key
        run: echo "CACHE_KEY=${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}" >> $GITHUB_ENV

      - name: Restore Python packages from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}

      - name: Scrape ${{ matrix.source }}
        run: |
          make scrape LIMIT=50 BRANCH=main SITES=${{ matrix.source }}
