name: Scrape Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
  workflow_run:
    workflows: ["Setup Environment"]
    types:
      - completed

env:
  LANG: "es_ES.UTF-8"
  LANGUAGE: "es_ES:es"
  LC_ALL: "es_ES.UTF-8"

jobs:
  download-cache-key:
    runs-on: ubuntu-latest
    steps:
      - name: Download cache key
        uses: actions/download-artifact@v4
        with:
          name: cache-key

      - name: Read cache key
        id: read-cache-key
        run: |
          CACHE_KEY=$(cat cache_key.txt)
          echo "CACHE_KEY=${CACHE_KEY}" >> $GITHUB_ENV

  scrape:
    runs-on: ubuntu-latest
    needs: download-cache-key
    strategy:
      matrix:
        source: ["abc", "ultimahora", "lanacion", "cincodias"]
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v4

      - name: Restore Python packages from cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}

      - name: Scrape ${{ matrix.source }}
        run: |
          .venv/bin/python -m routines.scrape main 50 ${{ matrix.source }}
