on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
    
env:
  LANG: "es_ES.UTF-8"
  LANGUAGE: "es_ES:es"
  LC_ALL: "es_ES.UTF-8"

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      cache-key: ${{ steps.cache-python.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Cache Python packages
        id: cache-python
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: |
          sudo locale-gen es_ES.UTF-8
          sudo dpkg-reconfigure locales
          python -m pip install --upgrade pip
          python -m venv .venv
          .venv/bin/pip install -r requirements.txt
          echo 'XATA_API_KEY = "${{secrets.XATA_API_KEY}}"' >> .env
          echo 'XATA_DB_URL = "${{secrets.XATA_DB_URL}}"' >> .env

  scrape_abc:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Scrape ABC
        run: |
          .venv/bin/python -m routines.scrape main 50 abc

  scrape_ultimahora:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Scrape UltimaHora
        run: |
          .venv/bin/python -m routines.scrape main 50 ultimahora

  scrape_lanacion:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Scrape LaNacion
        run: |
          .venv/bin/python -m routines.scrape main 50 lanacion

  scrape_cincodias:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ needs.setup.outputs.cache-key }}
      - name: Scrape CincoDias
        run: |
          .venv/bin/python -m routines.scrape main 50 cincodias