name: Scrape Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
  workflow_run:
    workflows: ["Setup Environment"]
    types:
      - completed

env:
  LANG: "es_ES.UTF-8"
  LANGUAGE: "es_ES:es"
  LC_ALL: "es_ES.UTF-8"

jobs:
  download-cache-key:
    runs-on: ubuntu-latest
    steps:
      - name: Download cache key
        uses: actions/download-artifact@v3
        with:
          name: cache-key
      - name: Read cache key
        id: read-cache-key
        run: |
          CACHE_KEY=$(cat cache_key.txt)
          echo "CACHE_KEY=${CACHE_KEY}" >> $GITHUB_ENV

  scrape_abc:
    runs-on: ubuntu-latest
    needs: download-cache-key
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}
      - name: Scrape ABC
        run: |
          .venv/bin/python -m routines.scrape main 50 abc

  scrape_ultimahora:
    runs-on: ubuntu-latest
    needs: download-cache-key
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}
      - name: Scrape UltimaHora
        run: |
          .venv/bin/python -m routines.scrape main 50 ultimahora

  scrape_lanacion:
    runs-on: ubuntu-latest
    needs: download-cache-key
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}
      - name: Scrape LaNacion
        run: |
          .venv/bin/python -m routines.scrape main 50 lanacion

  scrape_cincodias:
    runs-on: ubuntu-latest
    needs: download-cache-key
    timeout-minutes: 31
    steps:
      - uses: actions/checkout@v3
      - name: Restore Python packages from cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ env.CACHE_KEY }}
      - name: Scrape CincoDias
        run: |
          .venv/bin/python -m routines.scrape main 50 cincodias
