name: Setup Environment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache Python packages
        id: cache-python
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}

      - name: Install dependencies
        run: |
          export LANG=es_ES.UTF-8
          python -m pip install --upgrade pip
          make venv
          
          echo "XATA_API_KEY=${{ secrets.XATA_API_KEY }}" >> .env
          echo "XATA_DB_URL=${{ secrets.XATA_DB_URL }}" >> .env
