name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

env:
  LANG: "es_ES.UTF-8"
  LANGUAGE: "es_ES:es"
  LC_ALL: "es_ES.UTF-8"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo locale-gen es_ES.UTF-8
          sudo dpkg-reconfigure locales
          python -m pip install --upgrade pip
          make clean
          make venv
          echo 'XATA_API_KEY="${{secrets.XATA_API_KEY}}"' >> .env
          echo 'XATA_DB_URL="${{secrets.XATA_DB_URL}}"' >> .env
      - name: Build and test
        run: |
          make test